cmd:    "arduino-builder"

targets:
    compile:
        cmd:    "arduino-builder"
        args:
            - -compile
            - -hardware C:\Users\alexm\personalpathprograms\arduino-PR-beta1.9-BUILD-107\hardware
            - -hardware C:\Users\alexm\AppData\Local\Arduino15\packages
            - -tools C:\Users\alexm\personalpathprograms\arduino-PR-beta1.9-BUILD-107\hardware\tools
            - -tools C:\Users\alexm\personalpathprograms\arduino-PR-beta1.9-BUILD-107\tools
            - -tools C:\Users\alexm\AppData\Local\Arduino15\packages
            - -libraries C:\Users\alexm\personalpathprograms\arduino-PR-beta1.9-BUILD-107\libraries
            - -fqbn esp32:esp32:esp32
            - -build-path build
            - -prefs=build.f_cpu=96000000L
            - -verbose
            - watch2/watch2.ino

    upload:
        cmd:    "arduino-cli"
        name:   "watch2.ino"
        args:
            - upload
            - -p COM9
            - -v
            - --fqbn esp32:esp32:esp32
            - -i build/watch2.ino.bin
    serialconsole:
        cmd:    "miniterm.py"
        args:
            - COM9
            - 115200

    chipid:
        cmd:    "esptool.py"
        args:
            - chip_id
